const LEAGUE_ID='1312170915835969536';
const S={league:null,users:[],rosters:[],traded:[],nfl:null,teams:[],players:null,prospects:[],prospectMeta:null,ktc:[],ktcMeta:null,selected:[[],[]]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const num=n=>Number(n||0).toLocaleString();
const fmt=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:2});
const exact=(s,k)=>Number(s?.[k]||0)+Number(s?.[`${k}_decimal`]||0)/100;
const rec=r=>`${r.settings?.wins||0}-${r.settings?.losses||0}${r.settings?.ties?`-${r.settings.ties}`:''}`;
const pf=r=>exact(r.settings,'fpts'), pa=r=>exact(r.settings,'fpts_against'), maxPf=r=>exact(r.settings,'ppts');
const winPct=r=>{const x=r.settings||{},g=(x.wins||0)+(x.losses||0)+(x.ties||0);return g?((x.wins||0)+(x.ties||0)*.5)/g:0};
const rounds=()=>Number(S.league?.settings?.draft_rounds||4);
const playoffTeams=()=>Number(S.league?.settings?.playoff_teams||Math.max(4,Math.ceil(S.teams.length/2)));
const nextSeason=()=>String(Number(S.league?.season||new Date().getFullYear())+1);
function ownerName(u){return u?.display_name||u?.username||'Unknown owner'}
function teamName(u,r){return u?.metadata?.team_name||u?.display_name||u?.username||`Roster ${r.roster_id}`}
function avatarUrl(id){return id?`https://sleepercdn.com/avatars/thumbs/${id}`:''}
function initials(n='?'){return n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function teamCell(t){if(!t)return'<span class="muted">Unknown</span>';const av=t.user?.avatar;return `<div class="team-cell">${av?`<img class="avatar" src="${avatarUrl(av)}" alt="">`:`<div class="avatar fallback">${initials(t.name)}</div>`}<div><div class="team-name">${esc(t.name)}</div><div class="owner">${esc(ownerName(t.user))}</div></div></div>`}
function setFeed(id,text,kind=''){const el=$(id);el.textContent=text;el.className=`feed ${kind}`}
function showBanner(msg=''){const b=$('#banner');b.textContent=msg;b.classList.toggle('hidden',!msg)}
async function api(path){const r=await fetch(path,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()}
async function sleeper(path){return api(`/api/sleeper?path=${encodeURIComponent(path)}`)}
function buildTeams(){const byId=new Map(S.users.map(u=>[u.user_id,u]));S.teams=S.rosters.map(r=>({roster:r,user:byId.get(r.owner_id),name:teamName(byId.get(r.owner_id),r)}))}
function teamByRoster(id){return S.teams.find(t=>Number(t.roster.roster_id)===Number(id))}
function standings(){return [...S.teams].sort((a,b)=>winPct(b.roster)-winPct(a.roster)||pf(b.roster)-pf(a.roster)||maxPf(b.roster)-maxPf(a.roster))}
function statusFor(t){const arr=standings(),seed=arr.findIndex(x=>x.roster.roster_id===t.roster.roster_id)+1;return seed&&seed<=playoffTeams()?`Playoff seed ${seed}`:'Non-playoff'}
function projectedOrder(){const mode=$('#orderMode')?.value||'playoff',arr=[...S.teams];if(mode==='maxpf')return arr.sort((a,b)=>maxPf(a.roster)-maxPf(b.roster)||winPct(a.roster)-winPct(b.roster));if(mode==='record')return arr.sort((a,b)=>winPct(a.roster)-winPct(b.roster)||maxPf(a.roster)-maxPf(b.roster));if(mode==='pf')return arr.sort((a,b)=>pf(a.roster)-pf(b.roster)||maxPf(a.roster)-maxPf(b.roster));const seeds=standings(),play=new Set(seeds.slice(0,Math.min(playoffTeams(),seeds.length)).map(t=>Number(t.roster.roster_id)));const non=arr.filter(t=>!play.has(Number(t.roster.roster_id))).sort((a,b)=>maxPf(a.roster)-maxPf(b.roster)||winPct(a.roster)-winPct(b.roster));const post=arr.filter(t=>play.has(Number(t.roster.roster_id))).sort((a,b)=>winPct(a.roster)-winPct(b.roster)||pf(a.roster)-pf(b.roster));return[...non,...post]}
function currentPickOwner(round,rosterId,season){const moves=S.traded.filter(p=>String(p.season)===String(season)&&Number(p.round)===Number(round)&&Number(p.roster_id)===Number(rosterId));return moves.length?Number(moves[moves.length-1].owner_id):Number(rosterId)}
function setupMeta(){const y=nextSeason();$('#leagueName').textContent=S.league.name||'Dynasty Tankathon';$('#leagueMeta').textContent=`Sleeper ${S.league.season} · ${S.rosters.length} teams · Week ${S.nfl?.week??'—'}`;$('#draftTitle').textContent=`${y} Rookie Draft Projection`;document.title=`${S.league.name||'Dynasty'} · Dynasty Tankathon V6`;$('#roundSelect').innerHTML=Array.from({length:rounds()},(_,i)=>`<option value="${i+1}">Round ${i+1}</option>`).join('');$('#mockRounds').innerHTML=Array.from({length:rounds()},(_,i)=>`<option value="${i+1}" ${i===1?'selected':''}>${i+1} rounds</option>`).join('')}
function renderDraft(){const y=nextSeason(),r=Number($('#roundSelect').value||1),order=projectedOrder();$('#draftBody').innerHTML=order.map((t,i)=>{const ownerId=currentPickOwner(r,t.roster.roster_id,y),cur=teamByRoster(ownerId)||t,moved=ownerId!==Number(t.roster.roster_id);return `<tr><td class="pick-num">${r}.${String(i+1).padStart(2,'0')}</td><td>${teamCell(t)}</td><td>${teamCell(cur)} ${moved?'<span class="badge moved">Traded</span>':'<span class="badge">Own</span>'}</td><td><span class="badge ${statusFor(t)!=='Non-playoff'?'playoff':''}">${esc(statusFor(t))}</span></td><td>${rec(t.roster)}</td><td><strong>${fmt(maxPf(t.roster))}</strong></td><td>${fmt(pf(t.roster))}</td></tr>`}).join('');const non=order.filter(t=>statusFor(t)==='Non-playoff').slice(0,6);$('#tankRace').innerHTML=non.map((t,i)=>`<div class="rank-row"><div class="rank-pos">${i+1}</div><div><strong>${esc(t.name)}</strong><small>${rec(t.roster)} · ${esc(ownerName(t.user))}</small></div><div class="rank-value">${fmt(maxPf(t.roster))}</div></div>`).join('')||'<div class="muted">No non-playoff teams.</div>';const leader=[...S.teams].sort((a,b)=>pf(b.roster)-pf(a.roster))[0],tank=[...S.teams].sort((a,b)=>maxPf(a.roster)-maxPf(b.roster))[0];$('#leagueSnapshot').innerHTML=`<div><span>PF Leader</span><strong>${leader?esc(leader.name):'—'}</strong></div><div><span>Lowest Max PF</span><strong>${tank?esc(tank.name):'—'}</strong></div><div><span>Playoff Spots</span><strong>${playoffTeams()}</strong></div><div><span>Traded Picks</span><strong>${S.traded.filter(p=>Number(p.owner_id)!==Number(p.roster_id)).length}</strong></div>`}
function renderStandings(){const arr=standings();$('#standingsBody').innerHTML=arr.map((t,i)=>`<tr><td><strong>${i+1}</strong></td><td>${teamCell(t)}</td><td>${rec(t.roster)}</td><td>${(winPct(t.roster)*100).toFixed(1)}%</td><td>${fmt(pf(t.roster))}</td><td>${fmt(pa(t.roster))}</td><td><strong>${fmt(maxPf(t.roster))}</strong></td><td>${i<playoffTeams()?'<span class="badge playoff">Playoff</span>':'—'}</td></tr>`).join('')}
function seasons(){const b=Number(S.league.season),s=new Set([b+1,b+2,b+3]);S.traded.forEach(p=>s.add(Number(p.season)));return[...s].filter(Boolean).sort()}
function renderCapital(){const sel=$('#capitalSeason'),old=sel.value;sel.innerHTML=seasons().map(y=>`<option ${String(y)===old?'selected':''}>${y}</option>`).join('');const y=sel.value||seasons()[0];$('#capitalGrid').innerHTML=S.teams.map(owner=>{const chips=[];for(const orig of S.teams)for(let r=1;r<=rounds();r++)if(currentPickOwner(r,orig.roster.roster_id,y)===Number(owner.roster.roster_id)){const own=Number(orig.roster.roster_id)===Number(owner.roster.roster_id);chips.push(`<span class="pick-chip ${own?'':'acquired'}">${y} R${r} · ${own?'Own':esc(orig.name)}</span>`)}return `<article class="capital-card"><h3>${esc(owner.name)}</h3><div class="owner">${esc(ownerName(owner.user))}</div><div class="picks">${chips.join('')||'<span class="muted">No picks found</span>'}</div></article>`}).join('')}
function renderTeams(){$('#teamGrid').innerHTML=S.teams.map(t=>`<article class="team-card" data-roster="${t.roster.roster_id}">${teamCell(t)}<div class="team-stats"><div class="mini"><span>Record</span><strong>${rec(t.roster)}</strong></div><div class="mini"><span>PF</span><strong>${fmt(pf(t.roster))}</strong></div><div class="mini"><span>Max PF</span><strong>${fmt(maxPf(t.roster))}</strong></div></div><button>View roster</button></article>`).join('');$$('[data-roster]').forEach(x=>x.addEventListener('click',()=>openTeam(Number(x.dataset.roster))))}
const prospectKey=()=>`dt-v6-prospects-${LEAGUE_ID}`;
function prospectList(){try{const x=JSON.parse(localStorage.getItem(prospectKey()));if(Array.isArray(x)&&x.length)return x}catch{}return S.prospects}
function renderProspects(){const list=prospectList();$('#prospectsBody').innerHTML=list.map((p,i)=>`<tr><td class="pick-num">${i+1}</td><td>${p.overallRank??'—'}</td><td><strong>${esc(p.name)}</strong></td><td><span class="pos">${esc(p.pos)}</span></td><td>${esc(p.school)}</td><td><button class="move-btn" data-move="up" data-i="${i}">↑</button> <button class="move-btn" data-move="down" data-i="${i}">↓</button></td></tr>`).join('');$$('[data-move]').forEach(b=>b.onclick=()=>{const a=prospectList().slice(),i=Number(b.dataset.i),j=b.dataset.move==='up'?i-1:i+1;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];localStorage.setItem(prospectKey(),JSON.stringify(a));renderProspects();renderMock()})}
function renderMock(){const p=prospectList(),order=projectedOrder(),rs=Number($('#mockRounds').value||2),y=nextSeason(),rows=[];let ix=0;for(let r=1;r<=rs;r++)for(let i=0;i<order.length;i++){const orig=order[i],owner=teamByRoster(currentPickOwner(r,orig.roster.roster_id,y))||orig,prospect=p[ix++];if(!prospect)break;rows.push(`<div class="mock-pick"><div class="num">${r}.${String(i+1).padStart(2,'0')}</div><div><strong>${esc(prospect.name)}</strong><div class="muted">${esc(owner.name)}${owner!==orig?` · via ${esc(orig.name)}`:''}</div></div><span class="pos">${esc(prospect.pos)}</span></div>`)}$('#mockBoard').innerHTML=rows.join('')||'<div class="muted">Prospects are not loaded yet.</div>'}
async function ensurePlayers(){if(S.players)return S.players;S.players=await sleeper('/players/nfl');return S.players}
async function openTeam(id){const t=teamByRoster(id);$('#modalTitle').textContent=t?.name||'Roster';$('#modalBody').innerHTML='<p class="muted">Loading roster…</p>';$('#modal').classList.remove('hidden');try{const players=await ensurePlayers(),starters=new Set(t.roster.starters||[]),ids=t.roster.players||[],rows=ids.map(pid=>{const p=players[pid]||{};return {name:p.full_name||`${p.first_name||''} ${p.last_name||''}`.trim()||pid,pos:p.position||'—',team:p.team||'FA',starter:starters.has(pid)}}).sort((a,b)=>Number(b.starter)-Number(a.starter)||a.pos.localeCompare(b.pos)||a.name.localeCompare(b.name));$('#modalBody').innerHTML=rows.map(p=>`<div class="player-row"><span class="pos">${esc(p.pos)}</span><div><strong>${esc(p.name)}</strong><small>${esc(p.team)}</small></div>${p.starter?'<span class="badge playoff">Starter</span>':''}</div>`).join('')}catch(e){$('#modalBody').innerHTML=`<p class="muted">Roster player directory failed: ${esc(e.message)}</p>`}}
function normalizeName(s=''){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(jr|sr|ii|iii|iv)\b/g,'').replace(/[^a-z0-9]/g,'')}
function ktcFindPlayer(name,pos){const n=normalizeName(name);let exact=S.ktc.find(p=>normalizeName(p.name)===n&&(!pos||p.position===pos));if(exact)return exact;return S.ktc.find(p=>normalizeName(p.name)===n)||null}
function ktcValue(asset){if(asset.manualValue!=null)return Number(asset.manualValue)||0;const fmtKey=$('#tradeFormat').value;const row=asset.ktc||null;return Number(row?.[fmtKey]?.value||0)}
function pickTierForOriginal(rosterId){const order=projectedOrder(),ix=order.findIndex(t=>Number(t.roster.roster_id)===Number(rosterId)),n=order.length;if(ix<0)return'Mid';if(ix<n/3)return'Early';if(ix<2*n/3)return'Mid';return'Late'}
function roundWord(r){return['','1st','2nd','3rd','4th','5th'][r]||`${r}th`}
function ktcFindPick(year,round,origRoster){const tier=pickTierForOriginal(origRoster),target=normalizeName(`${year} ${tier} ${roundWord(round)}`);return S.ktc.find(p=>p.position==='PICK'&&normalizeName(p.name).includes(target))||S.ktc.find(p=>p.position==='PICK'&&normalizeName(p.name).includes(normalizeName(`${year} ${roundWord(round)}`)))||null}
async function assetsForTeam(team){const players=await ensurePlayers(),arr=[];for(const pid of team.roster.players||[]){const p=players[pid]||{},name=p.full_name||`${p.first_name||''} ${p.last_name||''}`.trim();if(!name||!['QB','RB','WR','TE'].includes(p.position))continue;arr.push({id:`p-${pid}`,type:'player',name,pos:p.position,team:p.team||'FA',ktc:ktcFindPlayer(name,p.position)})}for(const y of seasons())for(const orig of S.teams)for(let r=1;r<=rounds();r++)if(currentPickOwner(r,orig.roster.roster_id,y)===Number(team.roster.roster_id)){arr.push({id:`pick-${y}-${r}-${orig.roster.roster_id}`,type:'pick',name:`${y} ${pickTierForOriginal(orig.roster.roster_id)} ${roundWord(r)}`,pos:'PICK',team:`via ${orig.name}`,ktc:ktcFindPick(y,r,orig.roster.roster_id)})}return arr.sort((a,b)=>ktcValue(b)-ktcValue(a))}
async function renderTradeAssets(side){const select=$(`#tradeTeam${side}`),team=teamByRoster(Number(select.value));if(!team)return;const q=$(`#search${side}`).value.trim().toLowerCase(),assets=await assetsForTeam(team);$(`#assets${side}`).innerHTML=assets.filter(a=>!q||`${a.name} ${a.pos} ${a.team}`.toLowerCase().includes(q)).slice(0,80).map(a=>`<div class="asset-option" data-side="${side}" data-id="${esc(a.id)}"><div><strong>${esc(a.name)}</strong><small>${esc(a.pos)} · ${esc(a.team)}${a.ktc?'':' · KTC value unavailable'}</small></div><div class="asset-value">${num(ktcValue(a))}</div></div>`).join('');$$(`#assets${side} [data-id]`).forEach(el=>el.onclick=async()=>{const a=assets.find(x=>x.id===el.dataset.id);if(a&&!S.selected[side-1].some(x=>x.id===a.id)){S.selected[side-1].push(a);renderSelected();await renderTradeAssets(side)}})}
function renderSelected(){[1,2].forEach(side=>{$(`#selected${side}`).innerHTML=S.selected[side-1].map(a=>`<div class="selected-asset"><div><strong>${esc(a.name)}</strong><small>${esc(a.pos)} · ${esc(a.team)}</small></div><div><span class="asset-value">${num(ktcValue(a))}</span> <button class="remove" data-rside="${side}" data-rid="${esc(a.id)}">×</button></div></div>`).join('');$(`#total${side}`).textContent=num(S.selected[side-1].reduce((s,a)=>s+ktcValue(a),0))});$$('[data-rid]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.rside)-1;S.selected[i]=S.selected[i].filter(a=>a.id!==b.dataset.rid);renderSelected();renderTradeAssets(i+1)});const a=S.selected[0].reduce((s,x)=>s+ktcValue(x),0),b=S.selected[1].reduce((s,x)=>s+ktcValue(x),0),max=Math.max(a,b,1),gap=b-a,pct=Math.abs(gap)/max*100;$('#meterFill').style.width=`${Math.max(5,Math.min(95,a/(a+b||1)*100))}%`;if(!a||!b){$('#tradeVerdict').textContent='Add assets to both sides';$('#tradeGap').textContent='';return}$('#tradeVerdict').textContent=pct<=5?'Values are close':gap>0?'Team 1 receives more KTC value':'Team 2 receives more KTC value';$('#tradeGap').textContent=`Gap: ${num(Math.abs(gap))} KTC points · ${pct.toFixed(1)}% of the larger side`}
function populateTradeTeams(){const opts=S.teams.map(t=>`<option value="${t.roster.roster_id}">${esc(t.name)}</option>`).join('');$('#tradeTeam1').innerHTML=opts;$('#tradeTeam2').innerHTML=opts;if(S.teams[1])$('#tradeTeam2').value=S.teams[1].roster.roster_id}
async function loadProspects(){setFeed('#tankFeed','Tankathon · loading');try{const d=await api('/api/prospects');S.prospects=d.prospects||[];S.prospectMeta=d;setFeed('#tankFeed',`Tankathon · ${d.mode}`,d.mode==='live'?'ok':'warn');$('#prospectStatus').textContent=`${d.count} fantasy-position prospects · ${d.mode} source`;$('#prospectStatus').className=`source-note ${d.mode==='live'?'good':'warn'}`;renderProspects();renderMock()}catch(e){setFeed('#tankFeed','Tankathon · failed','warn');$('#prospectStatus').textContent=`Prospect feed failed: ${e.message}`}}
async function loadKtc(){setFeed('#ktcFeed','KTC · loading');try{const d=await api('/api/ktc');S.ktc=d.players||[];S.ktcMeta=d;setFeed('#ktcFeed',`KTC · ${d.mode}`,d.mode==='live'?'ok':'warn');$('#tradeStatus').textContent=d.count?`${d.count} KTC assets loaded · ${d.mode} source`:`KTC live feed unavailable. Player/pick rows without a value will show 0; use the KTC link for the official calculator.`;$('#tradeStatus').className=`source-note ${d.count?'good':'warn'}`;renderTradeAssets(1);renderTradeAssets(2)}catch(e){setFeed('#ktcFeed','KTC · failed','warn');$('#tradeStatus').textContent=`KTC feed failed: ${e.message}`}}
function renderAll(){buildTeams();setupMeta();renderDraft();renderStandings();renderCapital();renderTeams();populateTradeTeams();renderMock()}
async function loadLeague(){setFeed('#sleeperFeed','Sleeper · loading');showBanner('');try{const [league,users,rosters,traded,nfl]=await Promise.all([sleeper(`/league/${LEAGUE_ID}`),sleeper(`/league/${LEAGUE_ID}/users`),sleeper(`/league/${LEAGUE_ID}/rosters`),sleeper(`/league/${LEAGUE_ID}/traded_picks`).catch(()=>[]),sleeper('/state/nfl').catch(()=>({}))]);if(!league||!rosters?.length)throw new Error('No roster data returned');Object.assign(S,{league,users,rosters,traded,nfl});renderAll();setFeed('#sleeperFeed','Sleeper · live','ok')}catch(e){setFeed('#sleeperFeed','Sleeper · failed','warn');showBanner(`Sleeper feed failed after the backend health check passed: ${e.message}. Test /api/sleeper directly from the same .vercel.app domain.`)}}
async function checkBackend(){
  try{
    const d=await api('/api/health');
    if(!d?.ok) throw new Error('Health endpoint returned an invalid response');
    return true;
  }catch(e){
    setFeed('#sleeperFeed','Backend · missing','warn');
    setFeed('#tankFeed','Tankathon · waiting','warn');
    setFeed('#ktcFeed','KTC · waiting','warn');
    showBanner('Vercel backend is not available. Open this site from your .vercel.app URL and confirm /api/health returns JSON. If /api/health is 404, the GitHub repo root or Vercel Root Directory is wrong.');
    return false;
  }
}
async function boot(){const backend=await checkBackend();if(!backend)return;await loadLeague();await Promise.all([loadProspects(),loadKtc()])}
$$('.tab').forEach(b=>b.onclick=async()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${b.dataset.tab}`));if(b.dataset.tab==='trade'){await ensurePlayers().catch(()=>{});renderTradeAssets(1);renderTradeAssets(2)}});
$('#refreshAll').onclick=()=>location.reload();$('#orderMode').onchange=()=>{renderDraft();renderMock();renderTradeAssets(1);renderTradeAssets(2)};$('#roundSelect').onchange=renderDraft;$('#capitalSeason').onchange=renderCapital;$('#mockRounds').onchange=renderMock;$('#runMock').onclick=renderMock;$('#resetProspects').onclick=()=>{localStorage.removeItem(prospectKey());renderProspects();renderMock()};$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};['tradeTeam1','tradeTeam2','tradeFormat'].forEach((id,i)=>$('#'+id).onchange=()=>{if(id==='tradeFormat')renderSelected();renderTradeAssets(id==='tradeTeam2'?2:1);if(id==='tradeFormat')renderTradeAssets(2)});$('#search1').oninput=()=>renderTradeAssets(1);$('#search2').oninput=()=>renderTradeAssets(2);$('#clearTrade').onclick=()=>{S.selected=[[],[]];renderSelected()};
boot();
